CREATE TABLE temp_epulet_korm_kozp_01
(
SZEKTOR VARCHAR2(100),
ESZKOZCSP VARCHAR2(100),
AGAZAT VARCHAR2(30),
EPULET NUMBER(10,3),
HASZNALT_EPULET_VASARLAS NUMBER(10,3),
EPULET_ATVET NUMBER(10,3),
EPULET_PENZUGYI_LIZING NUMBER(10,3),
count_szoroz NUMBER(10,3),
count_szoroz_1999 NUMBER(10,3)

)
;

CREATE TABLE logging
(
   created_on      VARCHAR2(30)
 , info 		   VARCHAR2 (30)
 , proc_name	   VARCHAR2 (30)	
 , message   	   VARCHAR2 (4000)
 , backtrace       CLOB

)
;


CREATE INDEX pim_cfc
ON PIM_FNN_CFC (LIFETIME, EV, ERTEK);
CREATE INDEX pim_grs
ON PIM_FNN_GRS (LIFETIME, EV, ERTEK);
CREATE INDEX pim_net
ON PIM_FNN_NET (LIFETIME, EV, ERTEK);